# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
# Intentionally left blank -- run on PRs against all branches.

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create keys.ts
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          RECAPTCHA3_SITE_KEY: ${{ secrets.RECAPTCHA3_SITE_KEY }}
        run: |
          echo "export const FIREBASE_API_KEY = '$FIREBASE_API_KEY'; export const RECAPTCHA3_SITE_KEY = '$RECAPTCHA3_SITE_KEY'" > src/environments/keys.ts

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: |
          npm install -g firebase-tools@latest
          firebase emulators:exec --only auth,firestore,storage --project aaronjonesii 'npm run test:headless'

      - name: Build
        run: npm run build:production

